### ISSUE TITLE
OneDrive Setup

### ISSUE THREAD

**Issue by Pacers31Colts18** [msfreaks/EvergreenAdmx#1]
When I run this, I always see a popup for OneDrive setup (even though I already have OneDrive setup on my PC). I believe it's cause it downloads the exe and then extracts, but anyway to disable this?

**Comment by msfreaks** [comment]
The admx files for OneDrive will only be present after installing OneDrive.
So the script checks for the newest OneDrive version online, compares that to the version it previously had, and if the online version is newer, it will download and install the new one to extract the admx files from it. After it is done it uninstalls OneDrive again.
There are two ways to work around this:
1. run it on a server system where you don't need OneDrive and run it as a scheduled task (system context, no popup)
2. disable the OneDrive admx functionality in the script (comment the 3 lines at the end of the script where it checks for OneDrive).

I recommend the 1st option, as that is what this script was meant for. Running it unattended on a non-workstation machine.

**Comment by msfreaks** [comment]
Actually, I'll leave this open for now as an enhancement.
I can check if OneDrive is installed before trying to download and install a newer version, then grab the admx from the local install if needed.

**Comment by msfreaks** [comment]
Fixed / Added in 2101.2
