### ISSUE TITLE
Error if OneDrive is not running, Script Stops

### ISSUE THREAD

**Issue by Vexxer1** [msfreaks/EvergreenAdmx#11]
I've noticed, running this script on a Server 2019 it stops after the OneDrive Setup. For some reason, Onedrive.exe is not launched for me. Then the Stop-Process at line 816 will also fail and stop the script.

My very simple fix would be:
Stop-Process -Name "OneDrive" -Force -ErrorAction SilentlyContinue

Of course a get-process ...  | stop-process would be nicer.

**Comment by msfreaks** [comment]
Added to new version which will be released shortly.
