### ISSUE TITLE
Citrix Workspace ADMX currently fail

### ISSUE THREAD

**Issue by Vexxer1** [msfreaks/EvergreenAdmx#12]
When downloading the Citrix Workspace ADMX, the process currently failes with:

WARNING: Language 'en-US' not found for 'Citrix Workspace App'. Processing 'en-US' instead.

Reason for this seems to be Line 1120

$sourceadmx = "$($env:TEMP)\citrixworkspaceapp\$([io.path]::GetFileNameWithoutExtension($evergreen.URI.Split("/")[-1].Split("?")[0]))\Configuration"

At the time of my execution, the $evergreen.URI had the value of:
https://downloads.citrix.com/19926/CitrixWorkspace_ADMX_Files_2109.1.zip?__gda__=exp=1636988266~acl=/*~hmac=328db70a42999e3af8e8699ac8a6995058b6d6d20e177742ecb1475b44889be7

That's why the split in Line 1120 currently resolves this as "*~hmac=328db70a42999e3af8e8699ac8a6995058b6d6d20e177742ecb1475b44889be7"

What works for me is modifying the Split's array index from -1 to -2. Then it gets the correct value of the Zip File name

**Comment by msfreaks** [comment]
Updated with a fix in the next release, which will be released soon, thanks!
