### ISSUE TITLE
Add Group Policy Template for Schannel (SSL settings)

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#13]
Please consider adding Group Policy Template for Schannel (SSL settings)
Here's the github repo
https://github.com/Crosse/SchannelGroupPolicy

**Comment by msfreaks** [comment]
Hi Jonathan, 

Thanks for the suggestion, but that repository does not have versioning or releases for that matter.
I cannot check for new versions.

Consider using the CustomPolicyStore option if your want to process this template, and update it yourself whenever you find the repo was updated.

Cheers,

Arjan
