### ISSUE TITLE
Citrix Workspace App doesn't work anymore

### ISSUE THREAD

**Issue by xenadmin** [msfreaks/EvergreenAdmx#15]
If I execute the following command, the result is an empty folder. 
```
PS C:\Windows\system32> EvergreenAdmx.ps1 -WorkingDirectory "C:\Users\axadmin\Downloads\ADMX" -Languages @("en-US") -UseProductFolders:$true -Include @("Citrix Workspace App")
Cannot convert value "Files.0" to type "System.Version". Error: "Input string was not in a correct format."
At C:\Program Files\WindowsPowerShell\Scripts\EvergreenAdmx.ps1:1120 char:9
+     if (-not $Version -or [version]$evergreen.Version -gt [version]$V ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
```

**Comment by msfreaks** [comment]
Looks like Citrix changed the filenaming convention.. again..

It used to be something like CitrixWorkspace_ADMX_Files_2202, for which I took 2202 as the version for this file.
It now is CitrixWorkspace_ADMX_Files, so no longer a version indicator.

For now, I am sorry, no fix for this on my end.

**Comment by JonathanPitre** [comment]
This is still broken even with the latest release. Here's the fix. I can submit a pull request if you prefer.

`function Get-CitrixWorkspaceAppAdmxOnline {
<#
    .SYNOPSIS
    Returns latest Version and Uri for Citrix Workspace App ADMX files
#>

    try {
        $ProgressPreference = 'SilentlyContinue'
        $url = "https://www.citrix.com/downloads/workspace-app/windows/workspace-app-for-windows-latest.html"
        # grab content
        $web = (Invoke-WebRequest -UseDefaultCredentials -Uri $url -UseBasicParsing -DisableKeepAlive -ErrorAction Ignore).RawContent
        # find line with ADMX download
        $str = ($web -split "`r`n" | Select-String -Pattern "_ADMX_")[0].ToString().Trim()
        # extract url from ADMX download string
        $URI = "https:$(((Select-String '(\/\/)([^\s,]+)(?=")' -Input $str).Matches.Value))"
        # grab version
        $VersionRegEx = "Version\: ((?:\d+\.)+(?:\d+)) \((.+)\)"
        $Version = ($web | Select-String -Pattern $VersionRegEx).Matches.Groups[1].Value
        $ShortVersion = ($web| Select-String -Pattern $VersionRegEx).Matches.Groups[2].Value
        # return evergreen object
        # return evergreen object
        return @{ Version = $Version; URI = $URI }
    }
    catch {
        Throw $_
    }
}

function Get-CitrixWorkspaceAppAdmx {
<#
    .SYNOPSIS
    Process Citrix Workspace App Admx files

    .PARAMETER Version
    Current Version present

    .PARAMETER PolicyStore
    Destination for the Admx files
#>

    param(
        [string]$Version,
        [string]$PolicyStore = $null,
        [string[]]$Languages = $null
    )

    $evergreen = Get-CitrixWorkspaceAppAdmxOnline
    $productname = "Citrix Workspace App"
    $productfolder = ""; if ($UseProductFolders) { $productfolder = "\$($productname)" }

    # see if this is a newer version
    if (-not $Version -or [version]$evergreen.Version -gt [version]$Version) {
        Write-Verbose "Found new version $($evergreen.Version) for '$($productname)'"

        # download and process
        $outfile = "$($WorkingDirectory)\downloads\$($evergreen.URI.Split("?")[0].Split("/")[-1])"
        try {
            # download
            $ProgressPreference = 'SilentlyContinue'
            Write-Verbose "Downloading '$($evergreen.URI)' to '$($outfile)'"
            Invoke-WebRequest -UseDefaultCredentials -Uri $evergreen.URI -UseBasicParsing -OutFile $outfile

            # extract
            Write-Verbose "Extracting '$($outfile)' to '$($env:TEMP)\citrixworkspaceapp'"
            Expand-Archive -Path $outfile -DestinationPath "$($env:TEMP)\citrixworkspaceapp" -Force

            # copy
            $sourceadmx = "$($env:TEMP)\citrixworkspaceapp\$($evergreen.URI.Split("/")[-2].Split("?")[0].SubString(0,$evergreen.URI.Split("/")[-2].Split("?")[0].IndexOf(".")))"
            $targetadmx = "$($WorkingDirectory)\admx$($productfolder)"
            Copy-Admx -SourceFolder $sourceadmx -TargetFolder $targetadmx -PolicyStore $PolicyStore -ProductName $productname -Languages $Languages

            # cleanup
            Remove-Item -Path "$($env:TEMP)\citrixworkspaceapp" -Recurse -Force

            return $evergreen
        }
        catch {
            Throw $_
        }
    } else {
        # version already processed
        return $null
    }
}
`

**Comment by msfreaks** [comment]
Thanks!
Just tested this and committed the code in the dev branch.

**Comment by JonathanPitre** [comment]
Nice! looking forward for the change to the prod branch!

**Comment by JonathanPitre** [comment]
Not to sound pushy or anything but since this is broken in the prod release, can you please update the production branch?

**Comment by msfreaks** [comment]
Done :)
