### ISSUE TITLE
Add Azure Virtual Desktop ADMX template

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#17]
Direct link here: https://aka.ms/avdgpo
Documentation: https://docs.microsoft.com/en-us/azure/virtual-desktop/shortpath

**Comment by msfreaks** [comment]
Hi Jonathan,

Thanks for the suggestion, but same issue as with the Schannel repo; there's no versioning on this .cab file, or it's referencing web page.
I cannot check for new versions.

Cheers,

Arjan

**Comment by JonathanPitre** [comment]
Even with no version information, we could still add the policy definitions files, I doubt the URL is gonna change. As long as we get the ADMX files.

**Comment by msfreaks** [comment]
The point being that if I can't see that the admx files in that Url are newer than the files present on the machine where the script is run, how do I decide to download it?
If there's no versioning one can assume it doesn't change, so it should be downloaded manually.

**Comment by JonathanPitre** [comment]
More settings added to the ADMX
https://learn.microsoft.com/en-us/azure/virtual-desktop/administrative-template?tabs=group-policy-domain

We could use the article update date as a reference for versioning?

Afterall, It's not that different from what's being done to track Adobe ADMX updates.

Please reconsider. Thanks.

**Comment by msfreaks** [comment]
How about this:
- download should be at https://aka.ms/avdgpo
- check the redirected Url for the download Url, which points to https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWG1Ww
- invoke a webrequest to the reedirected download location without redirection, and checking the headers

**Last-Modified                     Mon, 30 Jan 2023 04:07:02 GMT**

Which is the last modified date for the .CAB file?
