### ISSUE TITLE
Add latest Foxit ADMX

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#18]
https://kb.foxitsoftware.com/hc/en-us/articles/360040241112-Available-GPO-templates

**Comment by msfreaks** [comment]
Hi Jonathan,

Unfortunately, Foxit blocks anything that is not a browser from accessing their website.
This means we cannot use powershell to find if there's a new version and follow that link to the downloads.

Not even the "Copy web-request to Powershell" trick worked, so I'm lost here (https://www.powershellbros.com/powershell-tip-of-the-week-create-invoke-webrequest-from-chrome/).

Cheers,

Arjan
