### ISSUE TITLE
MS Edge

### ISSUE THREAD

**Issue by CyrosX** [msfreaks/EvergreenAdmx#2]
There seems to be a problem with the Microsoft Edge (URL):

````
Invoke-WebRequest : Der Remotename konnte nicht aufgelöst werden: 'msedge.sf.dl.delivery.mp.microsoft.com'
In C:\Program Files\WindowsPowerShell\Scripts\EvergreenAdmx.ps1:890 Zeichen:13
+             Invoke-WebRequest -Uri $evergreen.URI -UseBasicParsing -O ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
````
(Sorry for german, it says, the URL could not be resolved)
Thank you for the script!

**Comment by msfreaks** [comment]
Hi CyrosX, I can not reproduce that error. Could it have been a temporary glitch?
I get the url straight from the update point for Edge itself: https://edgeupdates.microsoft.com/api/products?view=enterprise and I just ran the script succesfully here.

**Comment by msfreaks** [comment]
Closed for lack of responses, and not able to reproduce
