### ISSUE TITLE
Get-MicrosoftEdgePolicyOnline does not work

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#23]
Get-MicrosoftEdgePolicyOnline does not work since it's looking for zip files but the ADMX are provided into a cab file.

**Comment by JonathanPitre** [comment]
I got a PR fix coming for this one so don't sweat it

**Comment by msfreaks** [comment]
I have this one fixed. Now focusing on Zoom and Citrix.

**Comment by JonathanPitre** [comment]
Unfortunately, this is still broken. I see the admx being downloaded but not copied to the admx product folder.

**Comment by JonathanPitre** [comment]
and I see the microsoftedgepolicy folder in %temp%
![image](https://user-images.githubusercontent.com/15003329/192417112-a96abee6-0acb-4fe7-922c-5b4cb9803507.png)

**Comment by msfreaks** [comment]
Indeed, needs more work. Works if you run the script a second time, including Edge. Looks like the first time the Expand.exe command runs, it fails.

**Comment by msfreaks** [comment]
Fixed in 2301.1
