### ISSUE TITLE
Fix cleanup for Google Chrome admx

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#25]
The folder **chromeadmx** and the file **policy_templates.zip** are left in the **%Temp%** folder after the script has been processed.

**Comment by JonathanPitre** [comment]
Still broken.
![image](https://user-images.githubusercontent.com/15003329/192417170-2ee12ed1-afae-4d5c-90ab-c7f71e4ffb55.png)

**Comment by msfreaks** [comment]
I cannot reproduce this using the 2209.1 version?
