### ISSUE TITLE
Add Citrix Connnection Quality Indicator ADMX

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#3]
Please add Citrix Connnection Quality Indicator ADMX templates

You can grab the download here
https://support.citrix.com/article/CTX220774

and the admx are available in the following folder once the product is installed

"${env:ProgramFiles(x86)}\Citrix\HDX\bin\Connection Quality Indicator"

The challenge is that you can't download the fille unless you have a Citrix account and that you need to install the product on top of the VDA in order to get the admx templates. So maybe it's best to host a copy of the ADMX in the github repo or something.

**Comment by JonathanPitre** [comment]
I am working on a script to automate the download and the install, you can track my progress here
https://github.com/JonathanPitre/Apps/blob/master/Citrix/Connection%20Quality%20Indicator/Install.ps1

**Comment by msfreaks** [comment]
Downloads behind authentication not supported, sorry
