### ISSUE TITLE
Windows 11 22H2 policy definitions msi installation failed

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#30]
I get the following error
![image](https://user-images.githubusercontent.com/15003329/212119595-98865dc5-8cff-4599-afe1-13e67e745817.png)

The msi still seems to install normally
![image](https://user-images.githubusercontent.com/15003329/212121130-f21beaf9-a01c-458e-8926-04370e035543.png)

and I see files in C:\Program Files (x86)\Microsoft Group Policy\Windows 11 September 2022 Update (22H2)\PolicyDefinitions
![image](https://user-images.githubusercontent.com/15003329/212121394-344ecfc7-2387-48ed-8a51-2e6bf5e8c7a8.png)

However, none of them gets copied over
![image](https://user-images.githubusercontent.com/15003329/212121527-6f65af47-d8c8-475e-ba68-f5df2c0d4e29.png)

**Comment by JonathanPitre** [comment]
Line 899 seems to be the issue

**Comment by Cryotize** [comment]
Similar issue here:

![Screenshot 2023-06-12 141531](https://github.com/msfreaks/EvergreenAdmx/assets/49732602/408c8a00-e6fd-449a-a973-44406f934912)

**Comment by JonathanPitre** [comment]
Possibly fixed with #42

**Comment by JonathanPitre** [comment]
@msfreaks Please close this issue.
