### ISSUE TITLE
Add Microsoft LAPS policy definitions

### ISSUE THREAD

**Issue by JonathanPitre** [msfreaks/EvergreenAdmx#31]
https://learn.microsoft.com/en-us/answers/questions/1246788/group-policy-for-new-microsoft-laps

**Comment by Karl-WE** [comment]
Hi @JonathanPitre  these should be included on patched systems, aren't they? 
reference: https://kaidojarvemets.com/windows-laps-new-group-policy-settings/

**Comment by JonathanPitre** [comment]
right but it still needs to be copied to the central group policies store.

**Comment by JonathanPitre** [comment]
Fixed with [Windows 11 23H2](https://github.com/msfreaks/EvergreenAdmx/issues/38) support

**Comment by JonathanPitre** [comment]
Fixed with [Windows 11 23H2](https://github.com/msfreaks/EvergreenAdmx/issues/38) support
