### ISSUE TITLE
Adobe ADMX Templates have moved

### ISSUE THREAD

**Issue by fourthborngoose** [msfreaks/EvergreenAdmx#37]
Hello.  I have discovered that Adobe, who seems to think that we all have unlimited budgets for their products, have moved the ADMX files to a new location.

As you have the Adobe ADMX policies coming from the FTP, which seems to not getting updates and as FTP is blocked as a Security risk in most places, I wanted to share the information that I located after pulling my hair our in clumps (insert mental image  of Otto von Scratchensniff and the Warner's Animaniacs) with the information and the source of this information.

Source:  https://www.adobe.com/devnet-docs/acrobatetk/tools/DesktopDeployment/gpo.html#gpo-registry-template

Continuous Track
[Acrobat Continuous track]
(https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/misc/AcrobatADMTemplate.zip). 
Use this for Acrobat 32-bit and 64-bit, 64-bit Reader, and the unified installer.
[Reader Continuous track]
(https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/misc/ReaderADMTemplate.zip)

Classic Track 2020
[Acrobat Classic track]
(https://ardownload2.adobe.com/pub/adobe/acrobat/win/Acrobat2020/misc/AcrobatADMTemplate.zip)
[Reader Classic track]
(https://ardownload2.adobe.com/pub/adobe/reader/win/Acrobat2020/misc/ReaderADMTemplate.zip)

Classic Track 2017
[Acrobat Classic track]
(https://ardownload2.adobe.com/pub/adobe/acrobat/win/Acrobat2017/misc/AcrobatADMTemplate.zip)
[Reader Classic track]
(https://ardownload2.adobe.com/pub/adobe/reader/win/Acrobat2017/misc/ReaderADMTemplate.zip)

Template preferences fall into these broad categories:
General enterprise settings: Features such as disabling updates and setting the default PDF handler.
Security: Application security features such as enhanced security, sandboxing, and JS controls.
TrustManager: Trusting Windows OS security zones as defined in Internet Explorer.
Digital Signatures: Adobe Acrobat Trust List integration.

**Comment by JonathanPitre** [comment]
@msfreaks Please close this issue.
