### ISSUE TITLE
Add Windows 11 23H2 support

### ISSUE THREAD

**Issue by robertRuncak** [msfreaks/EvergreenAdmx#38]
Please add Windows 11 23H2 support
https://www.microsoft.com/en-us/download/details.aspx?id=105667

**Comment by Karl-WE** [comment]
please mark this closed

**Comment by JonathanPitre** [comment]
yes it was overlooked, I'm already on the case, thanks!

**Comment by JonathanPitre** [comment]
@msfreaks Please close this issue.

**Comment by Karl-WE** [comment]
Tested and confirmed wonderful @JonathanPitre !
