### ISSUE TITLE
Windows 11 23H2 support

### ISSUE THREAD

**Issue by ibeerens** [msfreaks/EvergreenAdmx#43]
When executing "EvergreenAdmx.ps1 -Windows11Version "23H2" -workingdirectory "C:\_install\ADMX\_latest\" -Include "Windows 11" the following error is displayed:

C:\Program Files\WindowsPowerShell\Scripts\EvergreenAdmx.ps1 : Cannot validate argument on parameter 'Windows11Version'. The
argument "23H2" does not belong to the set "21H2,22H2" specified by the ValidateSet attribute. Supply an argument that is in the
set and then try the command again.
At line:1 char:37

It looks like 23H2 is not added to the latest release.

**Comment by JonathanPitre** [comment]
@ibeerens Unless you overwrite the content of EvergreenAdmx.ps1 with the last [commit](https://raw.githubusercontent.com/msfreaks/EvergreenAdmx/main/EvergreenAdmx.ps1), you're not getting the Windows 11 23H2 support. @msfreaks  The zip file in the release section is still outdated, could you please update it once you get the chance to review the code?

**Comment by ibeerens** [comment]
Thanks!

**Comment by JonathanPitre** [comment]
@msfreaks Please close this issue.
