### ISSUE TITLE
-Include @("Citrix Workspace App") doesn't work

### ISSUE THREAD

**Issue by xenadmin** [msfreaks/EvergreenAdmx#6]
HI, if I try to include "Citrix Workspace App" the script fails with an error, see screenshots below. The following command was used:
`EvergreenAdmx.ps1 -WorkingDirectory "C:\Users\xenadmin\Downloads\ADMX" -Languages @("de-DE", "en-US") -UseProductFolders:$true -Include @("Citrix Workspace App")`
![grafik](https://user-images.githubusercontent.com/12057348/132661273-ebbc0f93-61ea-4a67-9e25-4eeaf3891365.png)
![grafik](https://user-images.githubusercontent.com/12057348/132661304-b520f3cc-c112-4750-b98b-45b040684f4c.png)

**Comment by msfreaks** [comment]
Fixed in 2109.1

Thanks for reporting this!
