### ISSUE TITLE
Include BIS-F only downloads the ADMX, but not the ADML file

### ISSUE THREAD

**Issue by xenadmin** [msfreaks/EvergreenAdmx#7]
Include BIS-F only downloads the ADMX, but not the ADML file.
If I take a look into the downloads directory, the downloaded ZIP file contains the ADML file, so it must be missing during the extraction. 

![grafik](https://user-images.githubusercontent.com/12057348/132661514-cea849e1-2166-4292-829c-d202a6cf4f3f.png)

**Comment by msfreaks** [comment]
Fixed in 2109.1

Thanks for reporting this!
