### ISSUE TITLE
issue if Win10 ADMX files already installed

### ISSUE THREAD

**Issue by EckeD** [msfreaks/EvergreenAdmx#9]
hi,
I experienced an issue if on the computer this script is executed the ADMX files for another Win10 version are already installed:
![EvergreenAdmx-FolderError](https://user-images.githubusercontent.com/31133224/141768940-01e7f84b-2385-4fb4-a417-794fb090164b.JPG)
As you can see, somehow the two folders of the installed ADMX (20H2 and 21H1) are mixed together...

**Comment by msfreaks** [comment]
I'll add a note to the pre-requisites that all Windows 1x ADMX installs must be removed prior to running the script.
